# Generated by Django 5.2.11 on 2026-09-21 07:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wastes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AllocationRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rule_code", models.CharField(max_length=30, unique=True)),
                ("rule_name", models.CharField(max_length=100)),
                ("valid_from", models.DateField()),
                ("valid_to", models.DateField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Settlement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("settlement_month", models.DateField(unique=True)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "작성 중"),
                            ("SOURCE_LOADED", "데이터 불러오기 완료"),
                            ("VENDOR_CALCULATED", "업체 정산 완료"),
                            ("ALLOCATED", "사업부 배분 완료"),
                            ("VALIDATED", "검증 완료"),
                            ("CONFIRMED", "정산 확정"),
                            ("REPORT_GENERATED", "보고서 생성 완료"),
                            ("EMAIL_SENT", "메일 발송 완료"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="waste_settlements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-settlement_month"],
            },
        ),
        migrations.CreateModel(
            name="SettlementAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=50)),
                ("before", models.JSONField(blank=True, default=dict)),
                ("after", models.JSONField(blank=True, default=dict)),
                ("reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "settlement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="wastes.settlement",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SettlementSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_id", models.CharField(max_length=100)),
                ("weigh_date", models.DateTimeField()),
                ("waste_type", models.CharField(max_length=100)),
                ("transport_company", models.CharField(max_length=100)),
                ("disposal_company", models.CharField(max_length=100)),
                ("weight", models.DecimalField(decimal_places=3, max_digits=16)),
                ("weight_unit", models.CharField(default="kg", max_length=20)),
                ("vehicle_no", models.CharField(blank=True, max_length=30)),
                ("slip_no", models.CharField(blank=True, max_length=50)),
                ("source_reference", models.CharField(blank=True, max_length=200)),
                (
                    "settlement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sources",
                        to="wastes.settlement",
                    ),
                ),
            ],
            options={
                "ordering": ["weigh_date", "source_id"],
            },
        ),
        migrations.CreateModel(
            name="SettlementValidation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50)),
                ("passed", models.BooleanField()),
                ("message", models.TextField(blank=True)),
                ("checked_at", models.DateTimeField(auto_now=True)),
                (
                    "settlement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validations",
                        to="wastes.settlement",
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="SettlementVendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vendor_name", models.CharField(max_length=100)),
                ("waste_type", models.CharField(max_length=100)),
                (
                    "price_type",
                    models.CharField(
                        choices=[("TRANSPORT", "운반"), ("DISPOSAL", "처리")],
                        max_length=10,
                    ),
                ),
                ("weight", models.DecimalField(decimal_places=3, max_digits=16)),
                ("unit", models.CharField(max_length=20)),
                ("unit_price", models.DecimalField(decimal_places=4, max_digits=16)),
                ("price_valid_from", models.DateField()),
                ("price_valid_to", models.DateField(blank=True, null=True)),
                ("raw_amount", models.DecimalField(decimal_places=4, max_digits=20)),
                ("supply_amount", models.BigIntegerField()),
                ("vat_amount", models.BigIntegerField()),
                ("total_amount", models.BigIntegerField()),
                (
                    "settlement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendor_results",
                        to="wastes.settlement",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendor_results",
                        to="wastes.settlementsource",
                    ),
                ),
            ],
            options={
                "ordering": ["vendor_name", "waste_type", "price_type", "source_id"],
            },
        ),
        migrations.CreateModel(
            name="SettlementAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("business_unit", models.CharField(max_length=100)),
                (
                    "allocation_rate",
                    models.DecimalField(decimal_places=4, max_digits=7),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "raw_supply_amount",
                    models.DecimalField(decimal_places=4, max_digits=20),
                ),
                ("base_supply_amount", models.BigIntegerField()),
                ("supply_adjustment", models.IntegerField(default=0)),
                ("supply_amount", models.BigIntegerField()),
                (
                    "raw_vat_amount",
                    models.DecimalField(decimal_places=4, max_digits=20),
                ),
                ("base_vat_amount", models.BigIntegerField()),
                ("vat_adjustment", models.IntegerField(default=0)),
                ("vat_amount", models.BigIntegerField()),
                ("total_amount", models.BigIntegerField()),
                (
                    "vendor_result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to="wastes.settlementvendor",
                    ),
                ),
            ],
            options={
                "ordering": ["vendor_result_id", "sort_order", "business_unit"],
            },
        ),
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vendor_name", models.CharField(max_length=100, unique=True)),
                ("business_number", models.CharField(blank=True, max_length=20)),
                (
                    "vendor_type",
                    models.CharField(
                        choices=[
                            ("TRANSPORT", "운반"),
                            ("DISPOSAL", "처리"),
                            ("BOTH", "운반/처리"),
                        ],
                        max_length=10,
                    ),
                ),
                ("manager_name", models.CharField(blank=True, max_length=100)),
                ("manager_email", models.EmailField(blank=True, max_length=254)),
                ("mail_cc", models.TextField(blank=True)),
                ("mail_enabled", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "allocation_rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vendors",
                        to="wastes.allocationrule",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="settlementvendor",
            name="vendor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="wastes.vendor"
            ),
        ),
        migrations.CreateModel(
            name="VendorPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("waste_type", models.CharField(max_length=100)),
                (
                    "price_type",
                    models.CharField(
                        choices=[("TRANSPORT", "운반"), ("DISPOSAL", "처리")],
                        max_length=10,
                    ),
                ),
                ("unit_price", models.DecimalField(decimal_places=4, max_digits=16)),
                ("unit", models.CharField(default="kg", max_length=20)),
                ("valid_from", models.DateField()),
                ("valid_to", models.DateField(blank=True, null=True)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prices",
                        to="wastes.vendor",
                    ),
                ),
            ],
            options={
                "ordering": ["-valid_from", "vendor__vendor_name", "waste_type"],
            },
        ),
        migrations.CreateModel(
            name="AllocationRuleDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("business_unit", models.CharField(max_length=100)),
                (
                    "allocation_rate",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=7,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="wastes.allocationrule",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "business_unit"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("rule", "business_unit"),
                        name="unique_rule_business_unit",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="settlementsource",
            constraint=models.UniqueConstraint(
                fields=("settlement", "source_id"), name="unique_settlement_source"
            ),
        ),
        migrations.AddConstraint(
            model_name="settlementvalidation",
            constraint=models.UniqueConstraint(
                fields=("settlement", "code"), name="unique_settlement_validation"
            ),
        ),
        migrations.AddConstraint(
            model_name="settlementallocation",
            constraint=models.UniqueConstraint(
                fields=("vendor_result", "business_unit"),
                name="unique_result_business_unit",
            ),
        ),
        migrations.AddConstraint(
            model_name="settlementvendor",
            constraint=models.UniqueConstraint(
                fields=("source", "price_type"), name="unique_source_price_type"
            ),
        ),
        migrations.AddConstraint(
            model_name="vendorprice",
            constraint=models.UniqueConstraint(
                fields=("vendor", "waste_type", "price_type", "valid_from"),
                name="unique_vendor_price_start",
            ),
        ),
    ]
