# Generated by Django 5.2.11 on 2026-09-27 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wastes", "0002_allocationrule_settlement_settlementauditlog_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="settlementvendor",
            name="allocation_rule_code",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="settlementvendor",
            name="allocation_rule_name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
