# Generated by Django 5.2.11 on 2026-03-11 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Facility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sec",
                    models.CharField(max_length=50, unique=True, verbose_name="SEC"),
                ),
                ("company", models.CharField(max_length=100, verbose_name="업체")),
                ("environment", models.CharField(max_length=50, verbose_name="환경")),
                (
                    "manage_no",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="관리번호"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Substance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="물질명"),
                ),
                (
                    "operator",
                    models.CharField(
                        choices=[
                            ("=", "="),
                            ("!=", "!="),
                            ("<", "<"),
                            (">", ">"),
                            (">=", ">="),
                            ("<=", "<="),
                            ("[]", "[이상, 이하]"),
                            ("[)", "[이상, 미만)"),
                            ("(]", "(초과, 이하]"),
                            ("()", "(초과, 미만)"),
                        ],
                        max_length=10,
                        verbose_name="비교연산자",
                    ),
                ),
                ("val1", models.FloatField(verbose_name="값1 (최소)")),
                (
                    "val2",
                    models.FloatField(blank=True, null=True, verbose_name="값2 (최대)"),
                ),
                ("unit", models.CharField(max_length=20, verbose_name="단위")),
            ],
        ),
        migrations.CreateModel(
            name="MeasurementConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(default=True, verbose_name="필수측정여부"),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="integrated.facility",
                    ),
                ),
                (
                    "substance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="integrated.substance",
                    ),
                ),
            ],
            options={
                "unique_together": {("facility", "substance")},
            },
        ),
        migrations.CreateModel(
            name="DailyLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="측정날짜")),
                ("value", models.FloatField(verbose_name="측정값")),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="integrated.facility",
                    ),
                ),
                (
                    "substance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="integrated.substance",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "facility"],
                "unique_together": {("facility", "date", "substance")},
            },
        ),
    ]
