# Generated by Django 5.2.11 on 2026-03-13 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrated", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dailylog",
            options={},
        ),
        migrations.AlterModelOptions(
            name="measurementconfig",
            options={
                "verbose_name": "측정 설정",
                "verbose_name_plural": "측정 설정 리스트",
            },
        ),
        migrations.AlterUniqueTogether(
            name="dailylog",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="facility",
            name="company",
        ),
        migrations.RemoveField(
            model_name="facility",
            name="environment",
        ),
        migrations.RemoveField(
            model_name="facility",
            name="manage_no",
        ),
        migrations.AddField(
            model_name="dailylog",
            name="agency",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="dailylog",
            name="air_flow",
            field=models.FloatField(blank=True, null=True, verbose_name="풍량"),
        ),
        migrations.AddField(
            model_name="dailylog",
            name="collection_month",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="dailylog",
            name="emission_rate",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dailylog",
            name="gas_speed",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dailylog",
            name="gas_temp",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dailylog",
            name="humidity",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dailylog",
            name="moisture",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dailylog",
            name="o2_conc",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dailylog",
            name="pressure",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dailylog",
            name="sampling_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dailylog",
            name="sampling_time_text",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="dailylog",
            name="temp",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dailylog",
            name="weather",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="dailylog",
            name="wind_dir",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="dailylog",
            name="wind_speed",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="facility",
            name="capacity",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="용량"
            ),
        ),
        migrations.AddField(
            model_name="facility",
            name="common_name",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="라인 세부 방지(공통)",
            ),
        ),
        migrations.AddField(
            model_name="facility",
            name="company_no",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="업체번호"
            ),
        ),
        migrations.AddField(
            model_name="facility",
            name="diameter",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="직경"
            ),
        ),
        migrations.AddField(
            model_name="facility",
            name="exhaust",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="배기"
            ),
        ),
        migrations.AddField(
            model_name="facility",
            name="facility_no",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="시설번호"
            ),
        ),
        migrations.AddField(
            model_name="facility",
            name="line",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="라인"
            ),
        ),
        migrations.AddField(
            model_name="facility",
            name="line_exhaust",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="라인 배기"
            ),
        ),
        migrations.AddField(
            model_name="facility",
            name="prevent_no",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="방지시설번호"
            ),
        ),
        migrations.AddField(
            model_name="facility",
            name="status",
            field=models.CharField(
                default="운영", max_length=20, verbose_name="운영/폐쇄"
            ),
        ),
        migrations.AddField(
            model_name="facility",
            name="tms_yn",
            field=models.CharField(default="X", max_length=10, verbose_name="TMS"),
        ),
        migrations.AddField(
            model_name="facility",
            name="workplace",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="사업장"
            ),
        ),
        migrations.AlterField(
            model_name="dailylog",
            name="date",
            field=models.DateField(verbose_name="채취일자"),
        ),
        migrations.AlterField(
            model_name="dailylog",
            name="value",
            field=models.FloatField(verbose_name="농도"),
        ),
        migrations.AlterField(
            model_name="facility",
            name="sec",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="세부라인 방지시설"
            ),
        ),
        migrations.AlterField(
            model_name="measurementconfig",
            name="is_required",
            field=models.BooleanField(default=True, verbose_name="필수여부"),
        ),
        migrations.AlterField(
            model_name="substance",
            name="operator",
            field=models.CharField(
                choices=[
                    ("<=", "<="),
                    (">=", ">="),
                    ("<", "<"),
                    (">", ">"),
                    ("[]", "[ ] 사이"),
                    ("()", "( ) 사이"),
                ],
                default="<=",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="substance",
            name="unit",
            field=models.CharField(
                default="mg/Sm3", max_length=20, verbose_name="단위"
            ),
        ),
        migrations.AlterField(
            model_name="substance",
            name="val1",
            field=models.FloatField(verbose_name="기준값1"),
        ),
        migrations.AlterField(
            model_name="substance",
            name="val2",
            field=models.FloatField(blank=True, null=True, verbose_name="기준값2"),
        ),
        migrations.AlterUniqueTogether(
            name="dailylog",
            unique_together={("facility", "substance", "date")},
        ),
    ]
