# Generated by Django 5.2.11 on 2026-03-21 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrated", "0002_alter_dailylog_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="substance",
            name="formula",
            field=models.CharField(
                default="-",
                help_text="예시: (1*74.92/22.4)*1*60*24/10^6",
                max_length=250,
                verbose_name="계산식",
            ),
        ),
        migrations.AlterField(
            model_name="substance",
            name="operator",
            field=models.CharField(
                blank=True,
                choices=[
                    ("<=", "<="),
                    (">=", ">="),
                    ("<", "<"),
                    (">", ">"),
                    ("[]", "[ ] 사이"),
                    ("()", "( ) 사이"),
                ],
                default="<=",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="substance",
            name="val1",
            field=models.FloatField(
                blank=True, default=0, null=True, verbose_name="기준값1"
            ),
        ),
        migrations.AlterField(
            model_name="substance",
            name="val2",
            field=models.FloatField(
                blank=True, default=0, null=True, verbose_name="기준값2"
            ),
        ),
    ]
