# Generated by Django 5.2.11 on 2026-03-21 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrated", "0003_substance_formula_alter_substance_operator_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="substance",
            name="operator",
        ),
        migrations.AddField(
            model_name="substance",
            name="cycle",
            field=models.CharField(
                choices=[("매월", "매월"), ("분기", "분기"), ("반기", "반기")],
                default="매월",
                max_length=10,
                verbose_name="측정주기",
            ),
        ),
        migrations.AddField(
            model_name="substance",
            name="legal_type",
            field=models.CharField(
                choices=[("법적", "법적"), ("참고", "참고")],
                default="법적",
                max_length=10,
                verbose_name="법적구분",
            ),
        ),
        migrations.AlterField(
            model_name="substance",
            name="formula",
            field=models.CharField(default="-", max_length=250, verbose_name="계산식"),
        ),
        migrations.AlterField(
            model_name="substance",
            name="val1",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="substance",
            name="val2",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
