# Generated by Django 5.2.11 on 2026-03-21 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrated", "0004_remove_substance_operator_substance_cycle_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailylog",
            name="is_airflow_exceed",
            field=models.BooleanField(default=False, verbose_name="풍량초과여부"),
        ),
        migrations.AddField(
            model_name="dailylog",
            name="is_internal_exceed",
            field=models.BooleanField(default=False, verbose_name="사내기준초과"),
        ),
        migrations.AddField(
            model_name="dailylog",
            name="is_legal_exceed",
            field=models.BooleanField(default=False, verbose_name="법적기준초과"),
        ),
        migrations.AddField(
            model_name="dailylog",
            name="is_report_data",
            field=models.BooleanField(default=False, verbose_name="제출용여부"),
        ),
        migrations.AddField(
            model_name="facility",
            name="capacity_acmm",
            field=models.FloatField(
                blank=True, default=0, null=True, verbose_name="용량(ACMM)"
            ),
        ),
        migrations.AddField(
            model_name="facility",
            name="capacity_ncmm",
            field=models.FloatField(
                blank=True, default=0, null=True, verbose_name="용량(NCMM)"
            ),
        ),
        migrations.AddIndex(
            model_name="dailylog",
            index=models.Index(
                fields=["date", "facility", "substance"],
                name="integrated__date_82c66b_idx",
            ),
        ),
    ]
