# Generated by Django 5.2.11 on 2026-03-21 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrated", "0005_dailylog_is_airflow_exceed_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dailylog",
            name="is_airflow_exceed",
        ),
        migrations.RemoveField(
            model_name="dailylog",
            name="is_internal_exceed",
        ),
        migrations.RemoveField(
            model_name="dailylog",
            name="is_legal_exceed",
        ),
        migrations.AddField(
            model_name="dailylog",
            name="airflow_status",
            field=models.CharField(
                choices=[
                    ("정상", "정상"),
                    ("사내초과", "사내초과"),
                    ("법적초과", "법적초과"),
                ],
                default="정상",
                max_length=20,
                verbose_name="풍량상태",
            ),
        ),
        migrations.AddField(
            model_name="dailylog",
            name="substance_status",
            field=models.CharField(
                choices=[
                    ("정상", "정상"),
                    ("사내초과", "사내초과"),
                    ("법적초과", "법적초과"),
                ],
                default="정상",
                max_length=20,
                verbose_name="농도상태",
            ),
        ),
    ]
