# Generated by Django 5.2.11 on 2026-03-21 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrated", "0006_remove_dailylog_is_airflow_exceed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailylog",
            name="raw_substance_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="엑셀입력물질명"
            ),
        ),
        migrations.AlterField(
            model_name="dailylog",
            name="substance",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="integrated.substance",
            ),
        ),
    ]
