# Generated by Django 5.2.11 on 2026-02-28 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomerAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("asset_type", models.CharField(max_length=50)),
                ("balance", models.DecimalField(decimal_places=2, max_digits=15)),
                ("email", models.EmailField(max_length=254)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
