# Generated by Django 5.2.11 on 2026-03-08 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NicsNotice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "post_id",
                    models.CharField(max_length=20, unique=True, verbose_name="고유ID"),
                ),
                ("title", models.CharField(max_length=500, verbose_name="제목")),
                ("reg_date", models.DateField(verbose_name="등록일")),
                (
                    "content",
                    models.TextField(blank=True, null=True, verbose_name="본문내용"),
                ),
                (
                    "file_links",
                    models.TextField(blank=True, null=True, verbose_name="첨부파일"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "안전원 고시",
                "verbose_name_plural": "안전원 고시 목록",
                "ordering": ["-reg_date", "-post_id"],
            },
        ),
    ]
