# Generated by Django 5.2.11 on 2026-09-03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chemicals", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HandlerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("knoxid", models.CharField(max_length=100, unique=True, verbose_name="KNOX ID")),
                ("name", models.CharField(max_length=100, verbose_name="이름")),
                ("department", models.CharField(max_length=200, verbose_name="부서")),
                ("is_active", models.BooleanField(default=True, verbose_name="교육 대상")),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "취급자교육 대상자",
                "verbose_name_plural": "취급자교육 대상자",
                "ordering": ["department", "name"],
            },
        ),
        migrations.CreateModel(
            name="TrainingCompletion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target_year", models.PositiveSmallIntegerField(verbose_name="대상 연도")),
                ("is_completed", models.BooleanField(default=False, verbose_name="수료 여부")),
                ("completion_code", models.TextField(blank=True, verbose_name="수료코드")),
                ("completed_at", models.DateTimeField(blank=True, null=True, verbose_name="수료 처리 시각")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "handler",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_completions",
                        to="chemicals.handlerprofile",
                        verbose_name="대상자",
                    ),
                ),
            ],
            options={
                "verbose_name": "취급자교육 수료 현황",
                "verbose_name_plural": "취급자교육 수료 현황",
                "ordering": ["-target_year", "handler__department", "handler__name"],
            },
        ),
        migrations.CreateModel(
            name="CompletionSubmissionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completion_code", models.TextField(verbose_name="제출 수료코드")),
                ("submitted_at", models.DateTimeField(auto_now_add=True, verbose_name="제출 시각")),
                (
                    "completion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submission_logs",
                        to="chemicals.trainingcompletion",
                        verbose_name="수료 기록",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="제출자",
                    ),
                ),
            ],
            options={
                "verbose_name": "수료코드 제출 이력",
                "verbose_name_plural": "수료코드 제출 이력",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="trainingcompletion",
            constraint=models.UniqueConstraint(
                fields=("handler", "target_year"),
                name="unique_handler_training_year",
            ),
        ),
    ]
