# Generated by Django 5.2.11 on 2026-09-07 13:08

from django.db import migrations, models


def recalculate_final_completion(apps, schema_editor):
    TrainingCompletion = apps.get_model("chemicals", "TrainingCompletion")
    TrainingCompletion.objects.update(is_completed=False)


def restore_online_completion(apps, schema_editor):
    TrainingCompletion = apps.get_model("chemicals", "TrainingCompletion")
    TrainingCompletion.objects.update(is_completed=False)
    TrainingCompletion.objects.exclude(online_completion_code="").update(is_completed=True)


class Migration(migrations.Migration):

    dependencies = [
        ("chemicals", "0002_handlerprofile_trainingcompletion_and_log"),
    ]

    operations = [
        migrations.RenameField(
            model_name="trainingcompletion",
            old_name="completed_at",
            new_name="online_completed_at",
        ),
        migrations.RenameField(
            model_name="trainingcompletion",
            old_name="completion_code",
            new_name="online_completion_code",
        ),
        migrations.AddField(
            model_name="trainingcompletion",
            name="offline_application_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="오프라인교육 신청일자"
            ),
        ),
        migrations.AddField(
            model_name="trainingcompletion",
            name="offline_completion_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="오프라인교육 수료일자"
            ),
        ),
        migrations.AlterField(
            model_name="trainingcompletion",
            name="online_completion_code",
            field=models.TextField(blank=True, verbose_name="온라인교육 수료코드"),
        ),
        migrations.AlterField(
            model_name="trainingcompletion",
            name="online_completed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="온라인교육 수료 처리 시각"
            ),
        ),
        migrations.AlterField(
            model_name="completionsubmissionlog",
            name="completion_code",
            field=models.TextField(blank=True, verbose_name="제출 수료코드"),
        ),
        migrations.AlterField(
            model_name="trainingcompletion",
            name="is_completed",
            field=models.BooleanField(default=False, verbose_name="최종 수료 여부"),
        ),
        migrations.RunPython(recalculate_final_completion, restore_online_completion),
    ]
